name: Selenium IDE CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: dotnet restore 2-SeleniumIDE/SeleniumIde.sln
      
    - name: Build the solution
      run: dotnet build 2-SeleniumIDE/SeleniumIde.sln --no-restore
      
    - name: Run the test project
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test 2-SeleniumIDE/SeleniumIde.sln --no-build --verbosity normal
