name: Node.js CI

on:
  push:
    branches: [ main, 10-03-Library ]
  pull_request:
    branches: [ main, 10-03-Library ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting (if available)
      run: npm run lint --if-present

    - name: Run build
      run: npm run build --if-present

    - name: Install Playwright browsers
      run: |
        # Install system dependencies (cached by GitHub Actions)
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libxss1 \
          libasound2t64 \
          libgtk-3-0 \
          libx11-xcb1 \
          libxcb-dri3-0 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrender1 \
          libxtst6 \
          libxcb1 \
          libx11-6 \
          libxau6 \
          libxdmcp6 || true
        
        # Install only Chromium browser (faster than all browsers)
        npx playwright install chromium --with-deps || npx playwright install chromium

    - name: Start servers in background
      run: |
        # Start frontend server (port 3000)
        npm start &
        # Start backend API server (port 3030)
        npm run server &
        sleep 10
        # Check both servers are running
        curl -f http://localhost:3000 || exit 1
        curl -f http://localhost:3030/data || exit 1

    - name: Run Playwright tests
      run: npm test

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Check for outdated packages
      run: npm outdated || true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
