name: Build and Test

on:
  push:
    branches: [ main, 10-06-SeleniumWebDriver ]
  pull_request:
    branches: [ main, 10-06-SeleniumWebDriver ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Restore dependencies
      run: dotnet restore SeleniumBasicExercise.sln
      
    - name: Build solution
      run: dotnet build SeleniumBasicExercise.sln --no-restore --configuration Release
      
    - name: Run TestProject1 tests
      run: |
        echo "Running TestProject1 tests"
        dotnet test TestProject1/TestProject1.csproj --verbosity normal --logger "trx;LogFileName=TestProject1-results.trx"
        
    - name: Run TestProject2 tests
      run: |
        echo "Running TestProject2 tests"
        dotnet test TestProject2/TestProject2.csproj --verbosity normal --logger "trx;LogFileName=TestProject2-results.trx"
        
    - name: Run TestProject3 tests
      run: |
        echo "Running TestProject3 tests"
        dotnet test TestProject3/TestProject3.csproj --verbosity normal --logger "trx;LogFileName=TestProject3-results.trx"
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/TestResults/
        retention-days: 30
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts
        path: |
          **/bin/Release/
          **/obj/Release/
        retention-days: 7
