name: Selenium WebDriver CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Restore dependencies
      run: dotnet restore SeleniumBasicExercise.sln
      
    - name: Build solution
      run: dotnet build SeleniumBasicExercise.sln --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test SeleniumBasicExercise.sln --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/TestResults/
          **/coverage.cobertura.xml
        retention-days: 30
        
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Selenium Test Results
        path: '**/test-results.trx'
        reporter: dotnet-trx
